# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_schema.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'test_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11test_schema.proto\x12\x04test\"*\n\x0bTestMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"t\n\x15TestMessageWithNested\x12\x11\n\tstr_field\x18\x01 \x01(\t\x12\x11\n\tint_field\x18\x02 \x01(\x05\x12\x14\n\x0c\x64ouble_field\x18\x03 \x01(\x01\x12\x1f\n\x06nested\x18\x04 \x01(\x0b\x32\x0f.test.TestInner\"1\n\tTestInner\x12\x11\n\tinner_str\x18\x01 \x01(\t\x12\x11\n\tinner_int\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTMESSAGE']._serialized_start=27
  _globals['_TESTMESSAGE']._serialized_end=69
  _globals['_TESTMESSAGEWITHNESTED']._serialized_start=71
  _globals['_TESTMESSAGEWITHNESTED']._serialized_end=187
  _globals['_TESTINNER']._serialized_start=189
  _globals['_TESTINNER']._serialized_end=238
# @@protoc_insertion_point(module_scope)
